[project]
name = "nl2ml-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bitsandbytes>=0.45.5",
    "datasets>=3.6.0",
    "deepspeed>=0.16.7",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "mlflow>=2.22.0",
    "peft>=0.15.2",
    "setuptools>=80.7.1",
    "transformers>=4.51.3",
    "trl>=0.17.0",
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
